# Ref: https://github.com/marketplace/actions/repository-dispatch
name: Build WebsiteTrigger Target Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Build Stable Documentation
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PLOTNINE_WEBSITE }}
          repository: has2k1/plotnine.org
          event-type: push-plotnine-examples-main
